[[constraint]]
    name = "k8s.io/client-go"
    version = "kubernetes-1.10.0-beta.1"

[[constraint]]
    name = "k8s.io/api"
    version = "kubernetes-1.10.0-beta.1"

[[constraint]]
    name = "k8s.io/apimachinery"
    version = "kubernetes-1.10.0-beta.1"

[[constraint]]
    name = "github.com/golang/glog"
    branch = "master"

[[constraint]]
    name = "gopkg.in/yaml.v2"
    branch = "v2"

[prune]
    go-tests = true
    unused-packages = true