apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8swatch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8swatch
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8swatch
subjects:
- kind: ServiceAccount
  name: k8swatch
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8swatch
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8swatch
  labels:
    app: k8swatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8swatch
  template:
    metadata:
      labels:
        app: k8swatch
    spec:
      serviceAccount: k8swatch
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kind
      #           operator: "In"
      #           values:
      #           - "monitor"
      containers:
      # - image: uhub.service.ucloud.cn/pingcap/k8swatch:latest
      - image: localhost:5000/pingcap/k8swatch:latest
        name: k8swatch
        command:
          - /k8swatch
          - -alertmanager=http://alertmanager:9093
          # - -config=/etc/k8swatch/config.yml
          - -logtostderr
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 100m
            memory: 300Mi
