apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8swatch
  labels:
    app: k8swatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8swatch
  template:
    metadata:
      labels:
        app: k8swatch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kind
                operator: "In"
                values:
                - "monitor"
      containers:
      - image: uhub.service.ucloud.cn/pingcap/k8swatch
        name: k8swatch
        command: ["/bin/k8swatch","-alertmanager","http://alertmanager:9093","-logtostderr"]
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 100m
            memory: 300Mi

